repr() not found
gear-foundation/dapps-app pull request #48
Opened 2023-09-05 11:02 UTC by ewrvp7lv7

WasmBuilder::with_meta(ContractMetadata::repr())
  |                                              ^^^^ function or associated item not found in `ContractMetadata`
  |
  = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
  |
1 + use gmeta::Metadata;
  |

warning: unused import: `gmeta::Metadata`
 --> build.rs:3:5
  |
3 | use gmeta::Metadata;
  |     ^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

2023-09-05 11:38 UTC, shamilsan commented
Please don't forget to update **all `Cargo.toml`s**.

E.g.: https://github.com/gear-foundation/dapps-app/blob/master/io/Cargo.toml

2023-09-05 12:19 UTC, ewrvp7lv7 commented
state_mut().iter().map(|(k, v)| (*k, *v)).collect();
       |                                                   ^^^^^^^ value of type `((), (ActorId, u128))` cannot be built from `std::iter::Iterator<Item=(ActorId, u128)>`

2023-09-05 12:19 UTC, ewrvp7lv7 commented
state
  28 | |             .into_iter()
     | |             -^^^^^^^^^ `((), (gstd::ActorId, u128))` is not an iterator

2023-09-05 12:20 UTC, shamilsan commented on io/src/lib.rs
> +    type State = Out<(ActorId, u128)>;
Why not `Out<Vec<(ActorId, u128)>>?

2023-09-05 12:25 UTC, ewrvp7lv7 commented on io/src/lib.rs
> +    type State = Out<(ActorId, u128)>;
You're right! Thank you!

2023-09-06 19:07 UTC, fluiderson approved these changes

2023-09-07 07:00 UTC, shamilsan requested changes
⚠️ Please:

- [ ] Change the branch name from `a4-update-deps` to `update-deps`.
- [x] Write some sensible PR description.

2023-09-07 07:47 UTC, closed without merging